Notificações locais
GRR2020/curimba pull request #14
Opened 2020-11-22 19:08 UTC by guigonzalo

Se tiver um cartão recomendado, vai mostrar uma vez por semana na segunda as dez da manhã uma notificação mostrando o cartão.

2020-11-22 19:56 UTC, jimaeda requested changes
Ve o que voce acha válido

2020-11-22 19:56 UTC, jimaeda commented on lib/screens/home.dart
> +class HomeState extends State<Home> {
Fazer um `StatefulWidget` com o `BaseView` é meio que redundante, o `BaseView` cria e retorna já um `StatefulWidget`, recomendo manter como `StatelessWidget`
```suggestion
class Home extends StatelessWidget {
```

2020-11-22 19:56 UTC, jimaeda commented on lib/screens/create_card.dart
> +      //   Scaffold.of(context).showSnackBar(snackBar);
Hmmm, vai deixar de mostrar a SnackBar? se sim, acho melhor remover tudo

2020-11-22 19:56 UTC, jimaeda commented on lib/screens/home.dart
> +                  child: receiveNotifications == 0 ? Icon(Icons.notifications_none) : Icon(Icons.notifications_active),
Nessas linhas não daria consultar o `receiveNotifications` direto do model? Tipo `model.receiveNotifications`.
E fazer uma função para alterar o valor de `receiveNotifications` dentro do model?

2020-11-22 19:56 UTC, jimaeda commented on lib/screens/home.dart
> +    return;
Não daria para jogar isso para o ViewModel? Vendo a função parece coisa mais relacionada a lógica de dados do que lógica da view e nesse caso o context nem é usado

2020-11-22 19:56 UTC, jimaeda commented on lib/screens/home.dart
> +    return;
Daria para jogar o seguinte trecho da lógica para o ViewModel
```
handleNotifications(context, receiveNotifications);
setState(() {
  receiveNotifications = receiveNotifications == 0 ? 1 : 0;
});
```

2020-11-22 19:56 UTC, jimaeda commented on lib/helpers/notifications_helper.dart
> +    CardModel recommendedCard = await locator<RecommendedCardsViewModel>().getFirstCard();
Só uma coisa a notar, como os ViewModels estão muito atrelados ao State da view que ele é instanciado é meio que antipattern fazer isso aqui.
Pode deixar assim, só comentando mesmo.

2020-11-22 19:56 UTC, jimaeda commented on lib/view_models/sign_up_view_model.dart
> +      await locator<SharedPreferencesHelper>().setReceiveNotifications();
Precisa mesmo chamar essa função aqui?

2020-11-22 19:56 UTC, jimaeda commented on lib/view_models/sign_in_view_model.dart
> +    await locator<SharedPreferencesHelper>().setReceiveNotifications();
Precisa mesmo chamar essa função aqui?

2020-11-22 19:56 UTC, jimaeda commented on lib/helpers/shared_preferences_helper.dart
> +  }
Essa função não é utilizada

2020-11-22 19:56 UTC, jimaeda commented on lib/helpers/time_helper.dart
> +import 'package:timezone/timezone.dart' as tz;
Não dá conflito importar duas bibliotecas diferentes com o mesmo alias?

2020-11-28 13:10 UTC, guigonzalo commented on lib/screens/create_card.dart
> +      //   Scaffold.of(context).showSnackBar(snackBar);
Esses snackbar estavam bugando, dava erro de que não existia scaffold

2020-11-28 13:12 UTC, guigonzalo commented on lib/helpers/time_helper.dart
> +import 'package:timezone/timezone.dart' as tz;
Isso é direto da biblioteca XD

2020-11-28 13:45 UTC, jimaeda commented on lib/screens/create_card.dart
> +      //   Scaffold.of(context).showSnackBar(snackBar);
```
_scaffoldKey.currentState..showSnackBar(snackBar);
```
tenta trocar por isso
`_scaffoldKey` é a global key do Scaffold

2020-11-28 13:45 UTC, jimaeda commented on lib/helpers/time_helper.dart
> +import 'package:timezone/timezone.dart' as tz;
que coisa

2020-11-28 13:51 UTC, guigonzalo commented on lib/screens/home.dart
> +                  child: receiveNotifications == 0 ? Icon(Icons.notifications_none) : Icon(Icons.notifications_active),
Daria, vou dar uma mudada, mas precisaria da variável pq ela serve para mudar o estado do widget, no caso muda o ícone de notificações dependendo da opção do usuário

2020-11-28 13:54 UTC, guigonzalo commented on lib/screens/home.dart
> +class HomeState extends State<Home> {
é que aqui eu precisei fazer assim para mudar o ícone de notificações, acho que não da com stateless widget

2020-11-28 14:00 UTC, jimaeda commented on lib/screens/home.dart
> +                  child: receiveNotifications == 0 ? Icon(Icons.notifications_none) : Icon(Icons.notifications_active),
O `ChangeNotifier` ja faz isso. No ViewModel não tem uma função que é chamada `notifyAllListeners`? Então quando voce chama ela o `Consumer` de dados que está no BaseView vai atualizar a tela de acordo com os novos dados.
Por isso que eu tinha comentado que era redundante fazer um StatefullWidget com o BaseView.
Da uma olhada na tela de listagem de cartões e o ViewModel que é um bom exemplo.

2020-11-28 14:16 UTC, guigonzalo commented on lib/screens/home.dart
> +                  child: receiveNotifications == 0 ? Icon(Icons.notifications_none) : Icon(Icons.notifications_active),
Hmm, saqui, vou dar uma olhada

2020-11-28 15:24 UTC, guigonzalo commented on lib/helpers/notifications_helper.dart
> +    CardModel recommendedCard = await locator<RecommendedCardsViewModel>().getFirstCard();
Imaginei mesmo, mas como seria feito então? No shared preferences?

2020-11-28 19:00 UTC, jimaeda commented on lib/helpers/notifications_helper.dart
> +    CardModel recommendedCard = await locator<RecommendedCardsViewModel>().getFirstCard();
Teria que fazer ou no próprio repository, mas não sei ao certo a melhor a forma de fazer isso.
Talvez salvar no SharedPreferences o id do cartão a ser recomendado e consultar depois pelo repository, mas como eu tinha comentado acho que não precisa fazer isso agora

2020-12-13 11:36 UTC, jimaeda commented on test/helpers/time_helper_test.dart
> +      // });
![image](https://user-images.githubusercontent.com/49476436/102010663-445a1680-3d1e-11eb-931f-f232056c8003.png)

2020-12-16 00:08 UTC, guigonzalo commented on test/helpers/time_helper_test.dart
> +      // });
Perdão, porém "na minha máquina funciona"

2020-12-19 22:03 UTC, merged